const MODAL_BODY_TYPES = {
		FACE_RECOGNITION: "FACE_RECOGNITION",
		DEFAULT: "",
	},
	RIGHT_DRAWER_TYPES = {
		NOTIFICATION: "NOTIFICATION",
		CALENDAR_EVENTS: "CALENDAR_EVENTS",
	},
	CONFIRMATION_MODAL_CLOSE_TYPES = {
		LEAD_DELETE: "LEAD_DELETE",
	};
export { MODAL_BODY_TYPES, RIGHT_DRAWER_TYPES, CONFIRMATION_MODAL_CLOSE_TYPES };
